# Generated by Django 3.1.2 on 2020-10-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationphotos',
            old_name='caption',
            new_name='depiction',
        ),
    ]
