# Generated by Django 3.1.2 on 2020-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201009_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationphotos',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
